[package]
name = "bin"
version = "0.1.0"
authors = ["David Sutherland <davethecanuck@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "0.2"
structopt = { version = "0.2", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Using package alias to prevent name collision
utils_multiproc = { package = "multiproc", path = "../utils/multiproc" }

